SELECT DISTINCT



OOLA.LINE_ID, 
OOLA.PROMISE_DATE,
OOLA.REQUEST_DATE, 
OOLA.LINE_NUMBER, 
OOLA.OPEN_FLAG, 
OOLA.SHIPMENT_PRIORITY_CODE,
OOLA.ATTRIBUTE6 AS COF_LINE,

OOHA.ORDER_NUMBER,

HOLDS_ALL.CREATION_DATE, 
HOLDS_ALL.ORG_ID, 
HOLDS_ALL.RELEASED_FLAG, 
HOLDS_ALL.CREATED_BY,

MSIB.SEGMENT1,

HSA.HOLD_COMMENT,

HOLD_TYPES.TYPE_CODE,
HOLD_TYPES.MEANING AS TYPE_OF_HOLD

FROM 
DUAL,
APPS.OE_ORDER_LINES_ALL OOLA

INNER JOIN APPS.OE_ORDER_HEADERS_ALL OOHA
ON OOLA.HEADER_ID = OOHA.HEADER_ID

INNER JOIN APPS.OE_ORDER_HOLDS_ALL HOLDS_ALL
ON OOHA.HEADER_ID = HOLDS_ALL.HEADER_ID

INNER JOIN APPS.MTL_SYSTEM_ITEMS_B MSIB
ON OOLA.INVENTORY_ITEM_ID = MSIB.INVENTORY_ITEM_ID
AND OOLA.SHIP_FROM_ORG_ID = MSIB.ORGANIZATION_ID

INNER JOIN APPS.OE_HOLD_SOURCES_ALL HSA
ON HSA.HOLD_SOURCE_ID = HOLDS_ALL.HOLD_SOURCE_ID

INNER JOIN (
SELECT OEL.MEANING, OHD.HOLD_ID, OHD.TYPE_CODE
FROM APPS.OE_LOOKUPS OEL,
APPS.OE_HOLD_DEFINITIONS OHD
WHERE OEL.LOOKUP_TYPE = 'HOLD_TYPE'
AND OEL.LOOKUP_CODE = OHD.TYPE_CODE

)HOLD_TYPES

ON HOLD_TYPES.HOLD_ID = HSA.HOLD_ID

INNER JOIN (  
  SELECT OL.LOOKUP_CODE, OL.MEANING
  FROM APPS.OE_LOOKUPS OL
  WHERE OL.LOOKUP_TYPE='SHIPMENT_PRIORITY'
) LOOKUPS

ON LOOKUPS.LOOKUP_CODE = OOLA.SHIPMENT_PRIORITY_CODE
;


