SELECT

OOLA.LINE_ID,
OOLA.ORDERED_ITEM,
OOLA.FULFILLMENT_DATE,

MBL.SERIAL_NUMBER,
MBL.TEI_NUMBER,
MBL.SOFTWARE_VERSION,
MBL.SEQUENCE_NUMBER,

OOHA.CUST_PO_NUMBER,
OOHA.ORDER_NUMBER,

MSIB.DESCRIPTION,
MSIB.ITEM_TYPE,

WND.DELIVERY_ID,
WND.ULTIMATE_DROPOFF_DATE,

MPD.PACKED_QUANTITY,
MPD.CREATION_DATE,
MPD.PACK_STATION,
MPD.CARTON_NUMBER,

SHIP_TO.ADDRESS1,
SHIP_TO.CITY

FROM APPS.OE_ORDER_LINES_ALL OOLA

INNER JOIN APPS.MOTWMS_BUILD_LINES MBL
ON OOLA.LINE_ID = MBL.LINE_ID

INNER JOIN APPS.OE_ORDER_HEADERS_ALL OOHA
ON OOLA.HEADER_ID = OOHA.HEADER_ID

INNER JOIN APPS.MTL_SYSTEM_ITEMS_B MSIB
ON OOLA.INVENTORY_ITEM_ID = MSIB.INVENTORY_ITEM_ID
AND OOLA.SHIP_FROM_ORG_ID = MSIB.ORGANIZATION_ID

LEFT JOIN APPS.ECE_AR_TRX_LINES EATL
ON OOHA.ORDER_NUMBER = EATL.SALES_ORDER_NUMBER

LEFT JOIN APPS.WSH_NEW_DELIVERIES WND
ON EATL.DELIVERY_ID = WND.DELIVERY_ID

INNER JOIN APPS.MOTWMS_PACK_DATA MPD
ON OOLA.LINE_ID = MPD.LINE_ID
AND OOLA.INVENTORY_ITEM_ID  = MPD.INVENTORY_ITEM_ID


LEFT JOIN (
  SELECT OOHA.HEADER_ID,

  HPS.PARTY_SITE_ID,

  HZCA.CUST_ACCOUNT_ID,

  HP.PERSON_FIRST_NAME ||' '|| HP.PERSON_LAST_NAME AS CONTACT_NAME,

  HP.PARTY_NAME,

  HL.ADDRESS1,
  HL.CITY,
  HL.STATE, 
  HL.COUNTRY

  FROM APPS.OE_ORDER_HEADERS_ALL OOHA

  INNER JOIN APPS.HZ_CUST_ACCOUNTS_ALL HZCA
  ON OOHA.SHIP_TO_ORG_ID = HZCA.CUST_ACCOUNT_ID

  INNER JOIN APPS.HZ_CUST_ACCT_SITES_ALL HCASA
  ON HZCA.CUST_ACCOUNT_ID = HCASA.CUST_ACCOUNT_ID

  INNER JOIN APPS.HZ_CUST_SITE_USES_ALL HCSUA
  ON HCASA.CUST_ACCT_SITE_ID = HCSUA.CUST_ACCT_SITE_ID

  INNER JOIN APPS.HZ_PARTY_SITES HPS
  ON HCASA.PARTY_SITE_ID = HPS.PARTY_SITE_ID

  INNER JOIN APPS.HZ_PARTIES HP
  ON HPS.PARTY_ID = HP.PARTY_ID

  INNER JOIN APPS.HZ_LOCATIONS HL
  ON HPS.LOCATION_ID = HL.LOCATION_ID

  WHERE HCSUA.PRIMARY_FLAG = 'Y'
  AND HCSUA.SITE_USE_CODE = 'SHIP_TO'
) SHIP_TO

ON OOHA.HEADER_ID = SHIP_TO.HEADER_ID

ORDER BY OOLA.LINE_ID
;

SELECT
*
FROM 
APPS.MOTWMS_PACK_DATA;
