SELECT DISTINCT

OOLA.LINE_ID, 
OOLA.SHIPMENT_PRIORITY_CODE, 
OOLA.ORDERED_ITEM,
OOLA.ORDERED_QUANTITY,
OOLA.PROMISE_DATE,
OOLA.SCHEDULE_SHIP_DATE,
OOLA.REQUEST_DATE,
OOLA.SHIPPED_QUANTITY,
OOLA.ACTUAL_SHIPMENT_DATE,
OOLA.FLOW_STATUS_CODE,

OS.SET_NAME,

OOHA.ATTRIBUTE8 AS COF_LINE,

HOLD_TYPES.TYPE_CODE

FROM 
APPS.OE_ORDER_LINES_ALL OOLA

INNER JOIN APPS.OE_SETS OS
ON OOLA.SHIP_SET_ID = OS.SET_ID

INNER JOIN APPS.OE_ORDER_HEADERS_ALL OOHA
ON OOLA.HEADER_ID = OOHA.HEADER_ID

LEFT JOIN APPS.OE_ORDER_HOLDS_ALL HOLDS_ALL
ON OOHA.HEADER_ID = HOLDS_ALL.HEADER_ID

INNER JOIN APPS.OE_HOLD_SOURCES_ALL HSA
ON HSA.HOLD_SOURCE_ID = HOLDS_ALL.HOLD_SOURCE_ID

INNER JOIN (
SELECT OEL.MEANING, OHD.HOLD_ID, OHD.TYPE_CODE
FROM APPS.OE_LOOKUPS OEL,
APPS.OE_HOLD_DEFINITIONS OHD
WHERE OEL.LOOKUP_TYPE = 'HOLD_TYPE'
AND OEL.LOOKUP_CODE = OHD.TYPE_CODE

)HOLD_TYPES

ON HOLD_TYPES.HOLD_ID = HSA.HOLD_ID

ORDER BY OOLA.LINE_ID
;
