SELECT

OOLA.LINE_ID,
OOLA.CUST_PO_NUMBER,
OOLA.FULFILLMENT_DATE,
OOLA.ITEM_TYPE_CODE,
OOLA.ACTUAL_ARRIVAL_DATE,

OOHA.ORDER_NUMBER,

MSIB.SEGMENT1 AS PART_NUMBER,
MSIB.DESCRIPTION,
MSIB.ITEM_TYPE,

EATL.DELIVERY_ID,

SHIP_TO.ADDRESS1,
SHIP_TO.CITY,

SERIAL_NUMBERS.SERIAL_NUMBER,

WND.ULTIMATE_DROPOFF_DATE

FROM 
APPS.OE_ORDER_LINES_ALL OOLA

INNER JOIN APPS.OE_ORDER_HEADERS_ALL OOHA
ON OOLA.HEADER_ID = OOHA.HEADER_ID

INNER JOIN APPS.MTL_SYSTEM_ITEMS_B MSIB
ON OOLA.INVENTORY_ITEM_ID = MSIB.INVENTORY_ITEM_ID
AND OOLA.SHIP_FROM_ORG_ID = MSIB.ORGANIZATION_ID

LEFT JOIN APPS.ECE_AR_TRX_LINES EATL
ON OOHA.ORDER_NUMBER = EATL.SALES_ORDER_NUMBER

INNER JOIN (
  SELECT OOHA.HEADER_ID,

  HPS.PARTY_SITE_ID,

  HZCA.CUST_ACCOUNT_ID,

  HP.PERSON_FIRST_NAME ||' '|| HP.PERSON_LAST_NAME AS CONTACT_NAME,

  HP.PARTY_NAME,

  HL.ADDRESS1,
  HL.CITY,
  HL.STATE, 
  HL.COUNTRY

  FROM APPS.OE_ORDER_HEADERS_ALL OOHA

  INNER JOIN APPS.HZ_CUST_ACCOUNTS_ALL HZCA
  ON OOHA.SHIP_TO_ORG_ID = HZCA.CUST_ACCOUNT_ID

  INNER JOIN APPS.HZ_CUST_ACCT_SITES_ALL HCASA
  ON HZCA.CUST_ACCOUNT_ID = HCASA.CUST_ACCOUNT_ID

  INNER JOIN APPS.HZ_CUST_SITE_USES_ALL HCSUA
  ON HCASA.CUST_ACCT_SITE_ID = HCSUA.CUST_ACCT_SITE_ID

  INNER JOIN APPS.HZ_PARTY_SITES HPS
  ON HCASA.PARTY_SITE_ID = HPS.PARTY_SITE_ID

  INNER JOIN APPS.HZ_PARTIES HP
  ON HPS.PARTY_ID = HP.PARTY_ID

  INNER JOIN APPS.HZ_LOCATIONS HL
  ON HPS.LOCATION_ID = HL.LOCATION_ID

  WHERE HCSUA.PRIMARY_FLAG = 'Y'
  AND HCSUA.SITE_USE_CODE = 'SHIP_TO'
) SHIP_TO

ON OOHA.HEADER_ID = SHIP_TO.HEADER_ID


LEFT JOIN (
  SELECT
  MUT.TRANSACTION_ID, 
  MSN.SERIAL_NUMBER, 
  MSN.INVENTORY_ITEM_ID, 
  MMT.TRX_SOURCE_LINE_ID

  FROM 
  APPS.MTL_SERIAL_NUMBERS MSN
  INNER JOIN APPS.MTL_UNIT_TRANSACTIONS MUT

  ON MSN.SERIAL_NUMBER = MUT.SERIAL_NUMBER
  AND MSN.INVENTORY_ITEM_ID = MUT.INVENTORY_ITEM_ID

  INNER JOIN APPS.MTL_MATERIAL_TRANSACTIONS MMT
  ON MUT.TRANSACTION_ID = MMT.TRANSACTION_ID
)SERIAL_NUMBERS

ON SERIAL_NUMBERS.TRX_SOURCE_LINE_ID = OOLA.LINE_ID

LEFT JOIN APPS.WSH_NEW_DELIVERIES WND
ON EATL.DELIVERY_ID = WND.DELIVERY_ID


ORDER BY OOLA.LINE_ID
;




