SELECT DISTINCT

MSIB.INVENTORY_ITEM_ID,
MSIB.SEGMENT1 AS ITEM_NUMBER,
MSIB.DESCRIPTION AS ITEM_DESCRIPTION,
MSIB.PRIMARY_UOM_CODE AS PRIMARY_UOM,
MOC.CONVERSION_RATE AS UOM_CONVERSION_FACTOR,
MSIB.ORGANIZATION_ID,
OOD.ORGANIZATION_NAME,
MO.ORGANIZATION_CODE,
ROUND(CIC.MATERIAL_COST,2) AS INPUT_COST_FUNCTIONAL,
ROUND(CIC.ITEM_COST,2) AS ITEM_COST,
GL.CURRENCY_CODE AS FUNCTIONAL_CURRENCY,
ROUND(NVL(EXCHANGE_RATES.CONVERSION_RATE, 1.00),6) AS CURRENCY_CONVERSION,
ROUND(CIC.MATERIAL_COST * NVL(EXCHANGE_RATES.CONVERSION_RATE, 1),2) AS INPUT_COST_USD,
ROUND(CIC.ITEM_COST * NVL(EXCHANGE_RATES.CONVERSION_RATE, 1),2) AS TOTAL_COST_USD,
NVL(ROUND(CIC.MATERIAL_COST * NVL(EXCHANGE_RATES.CONVERSION_RATE, 1),2) * MOC.CONVERSION_RATE,0) AS INPUT_COST_USD_PER_EA,
ROUND(GLOBAL_COST.MATERIAL_COST * NVL(EXCHANGE_RATES.CONVERSION_RATE, 1),2) AS GLOBAL_COST_USD,
NVL(ROUND(GLOBAL_COST.MATERIAL_COST * NVL(EXCHANGE_RATES.CONVERSION_RATE, 1),2) * MOC.CONVERSION_RATE,0) AS GLOBAL_COST_USD_PER_EA,
PLA.PO_LINE_ID,
ROUND(CIC.MATERIAL_COST,2) * PLA.QUANTITY AS FINAL_COST_FUNCTIONAL,
ROUND(CIC.MATERIAL_COST * NVL(EXCHANGE_RATES.CONVERSION_RATE, 1),2) * PLA.QUANTITY AS FINAL_COST_USD,
NVL(ROUND(CIC.MATERIAL_COST * NVL(EXCHANGE_RATES.CONVERSION_RATE, 1),2) * MOC.CONVERSION_RATE,0) * PLA.QUANTITY AS FINAL_COST_USD_PER_EA

FROM 
APPS.MTL_SYSTEM_ITEMS_B MSIB

INNER JOIN APPS.MTL_ORGANIZATIONS MO
ON MSIB.ORGANIZATION_ID = MO.ORGANIZATION_ID

INNER JOIN APPS.CST_ITEM_COSTS CIC
ON MSIB.INVENTORY_ITEM_ID = CIC.INVENTORY_ITEM_ID
AND CIC.ORGANIZATION_ID = CIC.ORGANIZATION_ID


INNER JOIN APPS.ORG_ORGANIZATION_DEFINITIONS OOD
ON MO.ORGANIZATION_ID = OOD.ORGANIZATION_ID

INNER JOIN APPS.GL_LEDGERS GL
ON OOD.SET_OF_BOOKS_ID = GL.LEDGER_ID

LEFT JOIN (
  SELECT
  SYSDATE,
  GDR.FROM_CURRENCY,
  GDR.TO_CURRENCY,
  GDR.CONVERSION_RATE

  FROM 
  DUAL,
  APPS.GL_DAILY_RATES GDR 
  WHERE CONVERSION_DATE = to_date(SYSDATE)

) EXCHANGE_RATES

ON EXCHANGE_RATES.FROM_CURRENCY = GL.CURRENCY_CODE
AND EXCHANGE_RATES.TO_CURRENCY = 'USD'

LEFT JOIN APPS.MTL_UOM_CONVERSIONS MOC
ON MSIB.INVENTORY_ITEM_ID = MOC.INVENTORY_ITEM_ID

LEFT JOIN 
  (
  SELECT
  INVENTORY_ITEM_ID, MATERIAL_COST
  FROM 
  APPS.CST_ITEM_COSTS
  WHERE ORGANIZATION_ID = 138
  ) GLOBAL_COST
  
ON MSIB.INVENTORY_ITEM_ID = GLOBAL_COST.INVENTORY_ITEM_ID

INNER JOIN APPS.PO_LINES_ALL PLA
ON MSIB.INVENTORY_ITEM_ID = PLA.ITEM_ID

ORDER BY MSIB.INVENTORY_ITEM_ID
