SELECT DISTINCT
OFAB.FUND_ID,
OFAB.START_DATE_ACTIVE AS OFFER_START_DATE,
OFAB.END_DATE_ACTIVE AS OFFER_END_DATE,
OFAB.STATUS_CODE AS OFFER_STATUS,
OFAB.CURRENCY_CODE_TC AS OFFER_CURRENCY,
OFAT.SHORT_NAME AS OFFER_NAME,
OFUAB.ACCTD_AMOUNT AS ULTILIZED_AMOUNT,
OOFS.COMMITTED_AMT AS COMMITTED_AMOUNT,
OFUAB.ACCTD_AMOUNT AS EARNED_AMOUNT,
QLHT.DESCRIPTION AS ACTIVITY,
OOLA.LINE_ID,
MSIB.SEGMENT1 AS ITEM_NUMBER,
MSIB.SEGMENT1 AS SUB_FAMILY,
MSIB.DESCRIPTION AS ITEM_DESCRIPTION,
MSIB.PRODUCT_FAMILY_ITEM_ID AS FAMILY,
ORG.NAME AS OU_NAME,
HZ.PARTY_NAME AS CUSTOMER_NAME,
HZ.ACCOUNT_NUMBER AS CUSTOMER_NUMBER,
CATEGORIES.SEGMENT12 AS SEGMENT,
GCC.SEGMENT5 AS WWAPC_CODE,
FLEX.DESCRIPTION AS PRODUCT_LINE,
FLEX.DESCRIPTION AS TECHNOLOGY,
FLEX.DESCRIPTION AS WWAPC


FROM 
APPS.OZF_FUNDS_ALL_B OFAB

INNER JOIN APPS.OZF_FUNDS_ALL_TL OFAT
ON OFAB.FUND_ID = OFAT.FUND_ID

INNER JOIN APPS.OZF_FUNDS_UTILIZED_ALL_B OFUAB
ON OFAB.FUND_ID = OFUAB.FUND_ID

INNER JOIN APPS.OZF_OBJECT_FUND_SUMMARY OOFS
ON OFAB.FUND_ID = OOFS.FUND_ID

INNER JOIN APPS.OZF_OFFERS OO
ON OFUAB.COMPONENT_ID = OO.QP_LIST_HEADER_ID

INNER JOIN APPS.QP_LIST_HEADERS_TL QLHT
ON OO.QP_LIST_HEADER_ID = QLHT.LIST_HEADER_ID

INNER JOIN APPS.OE_ORDER_LINES_ALL OOLA
ON OFUAB.ORDER_LINE_ID = OOLA.LINE_ID

INNER JOIN APPS.MTL_SYSTEM_ITEMS_B MSIB
ON OOLA.ORDERED_ITEM_ID = MSIB.INVENTORY_ITEM_ID
AND OOLA.SHIP_FROM_ORG_ID = MSIB.ORGANIZATION_ID

INNER JOIN (
  SELECT

  OOD.ORGANIZATION_ID AS ORG_ID, 
  OOD.ORGANIZATION_NAME,
  OOD.OPERATING_UNIT,
  HAOU.ORGANIZATION_ID AS HR_ORGANIZATION_ID,
  HAOU.NAME
  FROM 
  APPS.ORG_ORGANIZATION_DEFINITIONS OOD,
  APPS.HR_ALL_ORGANIZATION_UNITS HAOU

  WHERE OOD.OPERATING_UNIT = HAOU.ORGANIZATION_ID
) ORG

ON ORG.OPERATING_UNIT = OFAB.ORG_ID

INNER JOIN APPS.OE_ORDER_HEADERS_ALL OOHA
ON OOLA.HEADER_ID = OOHA.HEADER_ID

INNER JOIN (
  SELECT 
  
  OOHA.HEADER_ID,OOHA.ORDER_NUMBER,

  HZCA.ACCOUNT_NUMBER, HZCA.CUSTOMER_TYPE, 

  HCASA.CUST_ACCT_SITE_ID, 

  HCSUA.SITE_USE_ID,

  HPS.PARTY_SITE_ID,

  HP.PARTY_NAME, HP.PARTY_NUMBER,

  HL.STATE, HL.COUNTRY

  FROM APPS.OE_ORDER_HEADERS_ALL OOHA

  INNER JOIN APPS.HZ_CUST_ACCOUNTS_ALL HZCA
  ON OOHA.SHIP_TO_ORG_ID = HZCA.CUST_ACCOUNT_ID

  INNER JOIN APPS.HZ_CUST_ACCT_SITES_ALL HCASA
  ON HZCA.CUST_ACCOUNT_ID = HCASA.CUST_ACCOUNT_ID

  INNER JOIN APPS.HZ_CUST_SITE_USES_ALL HCSUA
  ON HCASA.CUST_ACCT_SITE_ID = HCSUA.CUST_ACCT_SITE_ID

  INNER JOIN APPS.HZ_PARTY_SITES HPS
  ON HCASA.PARTY_SITE_ID = HPS.PARTY_SITE_ID

  INNER JOIN APPS.HZ_PARTIES HP
  ON HPS.PARTY_ID = HP.PARTY_ID

  INNER JOIN APPS.HZ_LOCATIONS HL
  ON HPS.LOCATION_ID = HL.LOCATION_ID

  WHERE HCSUA.PRIMARY_FLAG = 'Y'
  AND HCSUA.SITE_USE_CODE = 'SHIP_TO'
) HZ

ON HZ.HEADER_ID = OOHA.HEADER_ID

INNER JOIN 
  (
  SELECT
  PLA.ITEM_ID,
  PLA.ITEM_DESCRIPTION,
  PLA.ORG_ID,
  PLA.CATEGORY_ID,
  MCB.SEGMENT12


  FROM 
  APPS.PO_LINES_ALL PLA
  LEFT JOIN APPS.MTL_CATEGORIES_B MCB
  ON MCB.CATEGORY_ID = PLA.CATEGORY_ID
  ) CATEGORIES
  
  ON MSIB.INVENTORY_ITEM_ID = CATEGORIES.ITEM_ID
  
INNER JOIN APPS.GL_CODE_COMBINATIONS GCC
ON MSIB.COST_OF_SALES_ACCOUNT = GCC.CODE_COMBINATION_ID

LEFT JOIN 
(
  SELECT 
  FV.FLEX_VALUE_ID,
  FV.FLEX_VALUE,
  fv.description 


  FROM apps.fnd_flex_values_vl fv,
  apps.fnd_flex_value_sets fvs 
  where FVS.FLEX_VALUE_SET_ID = FV.FLEX_VALUE_SET_ID 
  and FVS.FLEX_VALUE_SET_NAME = 'MSI_PROD_HIER_PROD_FAM_CODE'
) FLEX
ON TO_CHAR(MSIB.INVENTORY_ITEM_ID) = FLEX.FLEX_VALUE


WHERE OFAT.LANGUAGE = 'US'
;



