SELECT DISTINCT

OOLA.LINE_ID,

OOHA.ORDER_NUMBER, 
OOHA.BOOKED_DATE, 
OOHA.ORDER_CATEGORY_CODE, 
OOHA.FOB_POINT_CODE, 
OOHA.SHIPMENT_PRIORITY_CODE, 
OOHA.PARTIAL_SHIPMENTS_ALLOWED, 
OOHA.TRANSACTIONAL_CURR_CODE,
OOHA.CONVERSION_RATE, 
OOHA.ATTRIBUTE1 AS SALES_OFFICE, 
OOHA.FREIGHT_TERMS_CODE, 
OOHA.ATTRIBUTE5 AS ULT_DEST_COUNTRY_CODE,

OOLA.ITEM_TYPE_CODE, 
OOLA.SHIPPED_QUANTITY, 
OOLA.ORDERED_QUANTITY - OOLA.SHIPPED_QUANTITY AS TOTAL_UNSHIPPED_QTY,
OOLA.FLOW_STATUS_CODE, 
OOLA.SCHEDULE_SHIP_DATE, 
OOLA.SCHEDULE_ARRIVAL_DATE, 
OOLA.DELIVERY_LEAD_TIME,
OOLA.REQUEST_DATE,
OOLA.ACTUAL_SHIPMENT_DATE,

MSIB.SEGMENT1 AS ITEM_NUMBER, 
MSIB.PREPROCESSING_LEAD_TIME, 
MSIB.FULL_LEAD_TIME, 
MSIB.POSTPROCESSING_LEAD_TIME,
MSIB.PLANNING_MAKE_BUY_CODE, 
MSIB.SHIPPABLE_ITEM_FLAG,

HZ.ACCOUNT_NUMBER, 
HZ.CUSTOMER_TYPE,
HZ.PARTY_NAME, 
HZ.PARTY_NUMBER,
HZ.COUNTRY,

RCTA.PURCHASE_ORDER,

PLLA.PROMISED_DATE, 
PLLA.LEAD_TIME,
PLLA.COUNTRY_OF_ORIGIN_CODE,

HOU.NAME AS OPERATING_UNIT,

OHD.NAME AS HOLD_NAME,

RTT.NAME AS PAY_TERMS,

OS.SET_NAME,
OS.SET_ID,

OTTA.ATTRIBUTE12 AS BUSINESS,

OOLA.ORDERED_ITEM,

MSIB.DESCRIPTION,

MCB.SEGMENT15 AS PRODUCT_FAMILY_CODE, 
MCB.SEGMENT3 AS PRODUCT_SUB_FAMILY_CODE,

PPA.SEGMENT1 AS PROJECT_NUMBER,

CLASSES.ABC_CLASS_NAME,

ONHAND_QUANTITIES.ONHAND_QUANTITY,

MAD.ALLOCATED_QUANTITY,

MATP.QUANTITY_AVAILABLE,

SUBREGIONS.LOCATION_CODE,
SUBREGIONS.SUB_REGIONS,
DFF.VALUE_DESCRIPTION,
ORGANIZATIONS.ORGANIZATION_NAME,
GL.CURRENCY_CODE AS FUNCTIONAL_CURRENCY

FROM APPS.OE_ORDER_LINES_ALL OOLA
INNER JOIN APPS.OE_ORDER_HEADERS_ALL OOHA
ON OOLA.HEADER_ID = OOHA.HEADER_ID

INNER JOIN APPS.MTL_SYSTEM_ITEMS_B MSIB
ON OOLA.INVENTORY_ITEM_ID = MSIB.INVENTORY_ITEM_ID
AND OOLA.SHIP_FROM_ORG_ID = MSIB.ORGANIZATION_ID

INNER JOIN (
  SELECT 
  
  OOHA.HEADER_ID,OOHA.ORDER_NUMBER,

  HZCA.ACCOUNT_NUMBER, HZCA.CUSTOMER_TYPE, 

  HCASA.CUST_ACCT_SITE_ID, 

  HCSUA.SITE_USE_ID,

  HPS.PARTY_SITE_ID,

  HP.PARTY_NAME, HP.PARTY_NUMBER,

  HL.STATE, HL.COUNTRY

  FROM APPS.OE_ORDER_HEADERS_ALL OOHA

  INNER JOIN APPS.HZ_CUST_ACCOUNTS_ALL HZCA
  ON OOHA.SHIP_TO_ORG_ID = HZCA.CUST_ACCOUNT_ID

  INNER JOIN APPS.HZ_CUST_ACCT_SITES_ALL HCASA
  ON HZCA.CUST_ACCOUNT_ID = HCASA.CUST_ACCOUNT_ID

  INNER JOIN APPS.HZ_CUST_SITE_USES_ALL HCSUA
  ON HCASA.CUST_ACCT_SITE_ID = HCSUA.CUST_ACCT_SITE_ID

  INNER JOIN APPS.HZ_PARTY_SITES HPS
  ON HCASA.PARTY_SITE_ID = HPS.PARTY_SITE_ID

  INNER JOIN APPS.HZ_PARTIES HP
  ON HPS.PARTY_ID = HP.PARTY_ID

  INNER JOIN APPS.HZ_LOCATIONS HL
  ON HPS.LOCATION_ID = HL.LOCATION_ID

  WHERE HCSUA.PRIMARY_FLAG = 'Y'
  AND HCSUA.SITE_USE_CODE = 'SHIP_TO'
) HZ

ON HZ.HEADER_ID = OOHA.HEADER_ID

LEFT JOIN APPS.RA_CUSTOMER_TRX_LINES_ALL RCTLA
ON TO_CHAR(OOHA.ORDER_NUMBER) = RCTLA.INTERFACE_LINE_ATTRIBUTE1

LEFT JOIN APPS.RA_CUSTOMER_TRX_ALL RCTA
ON RCTLA.CUSTOMER_TRX_ID = RCTA.CUSTOMER_TRX_ID

LEFT JOIN APPS.PO_HEADERS_ALL PHA
ON RCTA.PURCHASE_ORDER = PHA.SEGMENT1

LEFT JOIN APPS.PO_LINE_LOCATIONS_ALL PLLA
ON PHA.PO_HEADER_ID = PLLA.PO_HEADER_ID

INNER JOIN APPS.HR_OPERATING_UNITS HOU
ON OOHA.ORG_ID = HOU.ORGANIZATION_ID

LEFT JOIN APPS.OE_ORDER_HOLDS_ALL OE_HOLDS
ON OOLA.LINE_ID = OE_HOLDS.LINE_ID

LEFT JOIN APPS.OE_HOLD_DEFINITIONS OHD
ON OE_HOLDS.ORDER_HOLD_ID = OHD.HOLD_ID

INNER JOIN APPS.RA_TERMS_TL RTT
ON OOLA.PAYMENT_TERM_ID = RTT.TERM_ID
AND RTT.LANGUAGE = 'US'

LEFT JOIN APPS.WSH_DELIVERY_DETAILS WDD
ON OOLA.LINE_ID = WDD.SOURCE_LINE_ID

LEFT JOIN APPS.OE_SETS OS
ON WDD.SHIP_SET_ID = OS.SET_ID

INNER JOIN APPS.OE_TRANSACTION_TYPES_ALL OTTA
ON OTTA.TRANSACTION_TYPE_ID = OOHA.ORDER_TYPE_ID

LEFT JOIN APPS.PO_LINES_ALL PLA
ON PHA.PO_HEADER_ID = PLA.PO_HEADER_ID

LEFT JOIN APPS.MTL_CATEGORIES_B MCB
ON PLA.CATEGORY_ID = MCB.CATEGORY_ID

LEFT JOIN APPS.PA_PROJECTS_ALL PPA
ON OOLA.PROJECT_ID = PPA.PROJECT_ID

LEFT JOIN (
  SELECT

  MAC.ABC_CLASS_ID, MAC.ABC_CLASS_NAME,

  MSI.INVENTORY_ITEM_ID, MSI.ORGANIZATION_ID


  FROM APPS.MSC_ABC_CLASSES MAC

  INNER JOIN APPS.MSC_SYSTEM_ITEMS MSI
  ON MAC.ABC_CLASS_ID = MSI.PLAN_ID
  AND MAC.SR_INSTANCE_ID = MSI.SR_INSTANCE_ID
) CLASSES

ON CLASSES.INVENTORY_ITEM_ID = MSIB.INVENTORY_ITEM_ID
AND CLASSES.ORGANIZATION_ID = MSIB.ORGANIZATION_ID


LEFT JOIN (

  SELECT

  MOQ.INVENTORY_ITEM_ID, MOQ.ORGANIZATION_ID, SUM(MOQ.TRANSACTION_QUANTITY) AS ONHAND_QUANTITY

  FROM APPS.MTL_ONHAND_QUANTITIES MOQ
  GROUP BY MOQ.INVENTORY_ITEM_ID, MOQ.ORGANIZATION_ID
) ONHAND_QUANTITIES

ON ONHAND_QUANTITIES.INVENTORY_ITEM_ID = MSIB.INVENTORY_ITEM_ID
AND ONHAND_QUANTITIES.ORGANIZATION_ID = MSIB.ORGANIZATION_ID


LEFT JOIN APPS.MSC_ALLOC_DEMANDS MAD
ON MAD.INVENTORY_ITEM_ID = MSIB.INVENTORY_ITEM_ID
AND MAD.ORGANIZATION_ID = MSIB.INVENTORY_ITEM_ID

LEFT JOIN APPS.MSC_AVAILABLE_TO_PROMISE MATP
ON MATP.INVENTORY_ITEM_ID = MSIB.INVENTORY_ITEM_ID
AND MATP.ORGANIZATION_ID = MSIB.ORGANIZATION_ID

INNER JOIN (
  SELECT
  HLA.LOCATION_ID, 
  HLA.LOCATION_CODE, 
  XRLH.SUB_REGIONS,
  HAOU.ORGANIZATION_ID

  FROM 
  APPS.HR_LOCATIONS_ALL HLA
  INNER JOIN APPS.XX_DRM_LOC_HIER XRLH
  ON HLA.COUNTRY = XRLH.COUNTRY
  INNER JOIN APPS.HR_ALL_ORGANIZATION_UNITS HAOU
  ON HLA.LOCATION_ID = HAOU.LOCATION_ID

) SUBREGIONS
ON SUBREGIONS.ORGANIZATION_ID = OOLA.SHIP_FROM_ORG_ID

LEFT JOIN (
  SELECT ffvs.flex_value_set_id ,
  ffvs.flex_value_set_name ,
  ffvs.description set_description ,
  ffvs.validation_type,
  ffv.flex_value,
  ffvt.description value_description,
  ffv.enabled_flag
  FROM apps.fnd_flex_value_sets ffvs ,
  apps.fnd_flex_values ffv ,
  apps.fnd_flex_values_tl ffvt
  WHERE
  ffvs.flex_value_set_id = ffv.flex_value_set_id
  and ffv.flex_value_id = ffvt.flex_value_id
  AND ffvt.language = USERENV('LANG')
  and flex_value_set_name like 'MSI_PROD_HIER_PROD_FAM_CODE'
  ORDER BY flex_value asc
 ) DFF
 ON DFF.FLEX_VALUE = MCB.SEGMENT3

INNER JOIN (
  SELECT
  OOD.ORGANIZATION_ID AS ORG_ID,
  OOD.SET_OF_BOOKS_ID,
  OOD.OPERATING_UNIT AS ORGANIZATION_ID,
  OOD.ORGANIZATION_NAME,
  HAOU.ORGANIZATION_ID AS HR_ORGANIZATION_ID,
  HAOU.NAME
  FROM 
  APPS.ORG_ORGANIZATION_DEFINITIONS OOD,
  APPS.HR_ALL_ORGANIZATION_UNITS HAOU

  WHERE OOD.OPERATING_UNIT = HAOU.ORGANIZATION_ID
) ORGANIZATIONS
ON ORGANIZATIONS.ORG_ID = OOLA.SHIP_FROM_ORG_ID

INNER JOIN APPS.GL_LEDGERS GL
ON ORGANIZATIONS.SET_OF_BOOKS_ID = GL.LEDGER_ID


ORDER BY OOLA.LINE_ID



;